apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               key: root-password
               name: mysql-pass
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               key: user
               name: mysql-pass
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               key: password
               name: mysql-pass
         - name: MYSQL_DATABASE
           value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
         claimName: mysql-pv-claim