apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    #targetPort: <Target Port>
